=== darktal91/tecweb.v2/data/eventi/eventi.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns="http://www.imperofiere.com"
targetNamespace="http://www.imperofiere.com" >
 
	<xs:element name="eventi" type="TEventi" >
		<xs:unique name="uniqueEventId">
			<xs:selector xpath="evento" />
			<xs:field xpath="id" />
		</xs:unique>
	</xs:element>


	<xs:complexType name="TEventi">
		<xs:sequence>
      			<xs:element name="evento" maxOccurs="unbounded" type="TEvento" />
    		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="TEvento">
		<xs:sequence>
			<xs:element name="id" type="xs:string" />
			<xs:element name="nome" type="xs:string" />
			<xs:element name="descrizione" type="xs:string" />
			<xs:element name="padiglione" type="xs:string" />
			<xs:element name="data" type="xs:date" />
			<xs:element name="inizio" type="xs:time" />
			<xs:element name="fine" type="xs:time" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== darktal91/tecweb.v2/data/eventi/eventi.xml
<?xml version="1.0"?>
<e:eventi xmlns:e="http://www.imperofiere.com" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="eventi.xsd">
	
	
	
	<evento>
		<id>RWx2aXMgUHJlc2xleQ==</id>
		<nome>Elvis Presley</nome>
		<descrizione>Elvis e un grande e a me mi piace atanto. Divertit con Elvis e ad ascolta musica bella che fa ballare ed e' yeah.</descrizione>
		<padiglione>A</padiglione>
		<data>2016-10-12</data>
		<inizio>12:12:00</inizio>
		<fine>13:12:00</fine>
	</evento>
	<evento>
		<id>RGFydGggVmFkZXI=</id>
		<nome>Darth Vader</nome>
		<descrizione>Il discorso tanto atteso di Dark Vader. Il discorso tanto atteso di Dark Vader.Il discorso tanto atteso di Dark Vader.Il discorso tanto atteso di Dark Vader.Il discorso tanto atteso di Dark Vader.Il discorso tanto atteso di Dark Vader.</descrizione>
		<padiglione>G</padiglione>
		<data>2016-05-12</data>
		<inizio>12:12:00</inizio>
		<fine>13:13:00</fine>
	</evento>
	<evento>
		<id>UXVhbGNvc2E=</id>
		<nome>Qualcosa</nome>
		<descrizione>Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test </descrizione>
		<padiglione>A</padiglione>
		<data>2016-05-05</data>
		<inizio>10:20:00</inizio>
		<fine>10:45:00</fine>
	</evento>
	<evento>
		<id>T3JkaW5hbWVudG9BWg==</id>
		<nome>OrdinamentoAZ</nome>
		<descrizione>Test OrdinamentoAZ Test OrdinamentoAZTest OrdinamentoAZTest OrdinamentoAZTest OrdinamentoAZTest OrdinamentoAZTest OrdinamentoAZTest OrdinamentoAZTest OrdinamentoAZTest OrdinamentoAZTest OrdinamentoAZTest OrdinamentoAZ</descrizione>
		<padiglione>G</padiglione>
		<data>2017-05-12</data>
		<inizio>12:15:00</inizio>
		<fine>19:15:00</fine>
	</evento>
</e:eventi>
