=== darktal91/tecweb.v2/data/acquisti/acquisti.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns="http://www.imperofiere.com"
  targetNamespace="http://www.imperofiere.com" >

<xs:element name="acquisti" type="Tacquisti"/>

  <xs:complexType name="Tacquisti">
    <xs:sequence>
      <xs:element name="tipologia" maxOccurs="unbounded" type="Ttipologia" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Ttipologia">
    <xs:sequence>
      <xs:element name="acquisto" minOccurs="0" maxOccurs="unbounded" type="Tacquisto" />
    </xs:sequence>
    <xs:attributeGroup ref="Ttipologiattr"/>
  </xs:complexType>
  
  <xs:attributeGroup name="Ttipologiattr">
    <xs:attribute name="id" type="Ttipo" use="required" />
		<xs:attribute name ="descrizione" type="xs:string" use="required" />
    <xs:attribute name="prezzo" type="Tprezzo" use="required" />
  </xs:attributeGroup>

  <xs:simpleType name="Ttipo">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="Tprezzo">
    <xs:restriction base="xs:double">
      <xs:minInclusive value="0.0"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:complexType name="Tacquisto">
    <xs:simpleContent>
      <xs:extension base="Tprezzo">
        <xs:attributeGroup ref="Tacquistoattr"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:attributeGroup name="Tacquistoattr">
    <xs:attribute name="username" type="xs:string" use="required" />
    <xs:attribute name="datatime" type="xs:dateTime" use="required" />
  </xs:attributeGroup>  
</xs:schema>

=== darktal91/tecweb.v2/data/acquisti/acquisti.xml
<?xml version="1.0" encoding="UTF-8"?>
<a:acquisti xmlns:a="http://www.imperofiere.com" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="http://www.imperofiere.com acquisti.xsd">
	<tipologia id="adulti" descrizione="Per chiunque almeno 16 anni, permette l'accesso completo a tutti i padiglioni" prezzo="150">
		<acquisto username="lbianchi" datatime="2016-09-05T21:04:44">1</acquisto>
		<acquisto username="mrossi" datatime="2016-09-05T21:08:58">1</acquisto>
		<acquisto username="user" datatime="2016-09-05T21:10:31">1</acquisto>
		<acquisto username="admin" datatime="2016-09-05T21:19:06">1</acquisto>
	</tipologia>
	<tipologia id="ragazzi" descrizione="Riservato ai ragazzi al di sotto dei 16 anni, permette l'accesso completo a tutti i padiglioni" prezzo="25">
		<acquisto username="lbianchi" datatime="2016-09-05T21:04:44">2</acquisto>
		<acquisto username="mrossi" datatime="2016-09-05T21:08:58">2</acquisto>
	</tipologia>
	<tipologia id="bambini" descrizione="Riservato ai bambini al di sotto dei 3 anni, i quali devono essere accompagnati da un adulto" prezzo="5">
		<acquisto username="lbianchi" datatime="2016-09-05T21:04:44">5</acquisto>
		<acquisto username="mrossi" datatime="2016-09-05T21:08:58">1</acquisto>
		<acquisto username="user" datatime="2016-09-05T21:10:31">1</acquisto>
	</tipologia>
	<tipologia id="anziani" descrizione="Riservato alle persone che abbiano compiuto i 65 anni, permette l'accesso completo a tutti i padiglioni" prezzo="15">
		<acquisto username="lbianchi" datatime="2016-09-05T21:04:44">1</acquisto>
		<acquisto username="mrossi" datatime="2016-09-05T21:08:58">4</acquisto>
	</tipologia>
</a:acquisti>
